defaults:
  - default.yaml

tag: 'causal-benchmark-labeled'

# NOTE: for training and validation, this is using the original (unmodified) scenarios
train_data_path: [ "${paths.base_path}/processed/mini_causal/training" ] # list of paths to the training data
train_data_tag: ["mini-causal-training"]
val_data_path: ["${paths.base_path}/processed/mini_causal/validation" ] # list of paths to the validation data
val_data_tag: ["mini-causal-validation"]

# NOTE: for testing, this is using the benchmark sets which are perturbed versions of the original scenes.
test_data_path: [
  "${paths.base_path}/processed/mini_causal/validation",
  "${paths.base_path}/processed/mini_causal/testing",
  "${paths.base_path}/processed/remove_noncausal/validation",
  "${paths.base_path}/processed/remove_noncausal/testing",
]
test_data_tag: [
  "mini-causal-validation",
  "mini-causal-testing",
  "remove-noncausal-validation",      # Perturbation: removes agents that are NOT causal to the ego.
  "remove-noncausal-testing",
]
